### ISSUE TITLE
Deprecation warning for Numpy

### ISSUE THREAD

**Issue by kramnda1** [Eric-Canas/qrdet#3]
Hello,

I am using your QReader and I get a deprecation warning for lines 73 and 74 in file _qrdet_helpers.py.

For reference just copying the warning that I get:

`./usr/local/lib/python3.9/site-packages/qrdet/_qrdet_helpers.py:73: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  confidence = float(boxes.conf)`

`./usr/local/lib/python3.9/site-packages/qrdet/_qrdet_helpers.py:74: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  assert int(boxes.cls) == 0, f'Expected class to be always 0, got {int(boxes.cls)}'`
  
Thanks

**Comment by Eric-Canas** [comment]
Hi!

I have just solved it on 2.4. It should disappear if you `pip install --upgrade qrdet`

Thanks a lot for the warning!
